### PR TITLE
Merge context package into the main package

### LINKED ISSUE #96: Merge context package with the main package
**Is your feature request related to a problem? Please describe.**
Currently the stdlib context and gobdd context packages can only be used in one file together with import aliases.

**Describe the solution you'd like**
Merge the context package with the main package. The functionality belongs closely together anyway.

**Describe alternatives you've considered**
Create an interface in the main package (interfaces belong to consumers).

Related #83

**Additional context**
This could be a backwards compatible change: we could keep the original package and add a type alias pointing to the new type in the root package.

### PR DESCRIPTION
**Pull request by sagikazarmark**
Fixes #96

This is a fully backwards compatible change by adding aliases for the necessary type (Context).

## ToDos

- [ ] `NewContext` does not have to be exported. Should it be?

## Possible alternatives

- Introduce an interface: that would be a somewhat backward incompatible change, but the Context should only be used by consumers as a type, it shouldn't be manually instantiated. (An interface can still be added after this PR)
- Add a type alias to the context package: would be less code change, but eventually the context package should go away

### CODE REVIEW

**Comment by bkielbasa** [comment]
thanks for your contribution!

I think we can remove the context package in v2.0.

IMO we can make `NewContext` unexported.

**Comment by sagikazarmark** [comment]
Oh, it looks like we cannot make `NewContext` unexported, if we want to keep `New` in the context package.

**Comment by bkielbasa** [comment]
please fix linter issues and I can merge it

**Comment by sagikazarmark** [comment]
One of the failing lint rules seems to be false positive.

**Comment by sagikazarmark** [comment]
```
gobdd.go:415:38: `t` can be `github.com/stretchr/testify/assert.TestingT` (interfacer)
func (def *stepDef) run(ctx Context, t TestingT, params [][]byte) {
```

I think this is false positive. I can either disable linting in this line with `// nolint: interfacer`, or disable the interfacer linter entirely.

**Comment by bkielbasa** [comment]
@sagikazarmark let's disable it for this line for now. If we'll have more problems like that we can disable it entirely.

**Comment by bkielbasa** [comment]
@sagikazarmark you don't have to rebase commits because I squash and merge them anyway :)

**Comment by bkielbasa** [comment]
Thanks for your contribution!

**Pull request merged**
