### PR TITLE
Use functional options

### PR DESCRIPTION
**Pull request by arberiii**
This will solve this [issue](https://github.com/go-bdd/gobdd/issues/49). Each of the options method will return a closure that changes the form of an options variable. Then in NewSuite function it start with default options and is passed to all closures in left to right order. Also changed the tests to work with the new API and all the tests passed!

I also added a minor modification runStep function, changed the format from %s %s to %s%s , as the former create unnecessary space.

### CODE REVIEW

**Comment by bkielbasa** [comment]
Awesome job!
Just one thing: recently, I put [docs](https://github.com/go-bdd/gobdd/tree/master/docs) to the main repo so please update the docs as well to keep it consistent.

**Comment by arberiii** [comment]
Thanks 😃 . I only found one place where the new format is inconsistent and changed the example in docs.

**Comment by bkielbasa** [comment]
Awesome! Thank you :)

**Comment by sagikazarmark** [comment]
Awesome! I still think that `WithBefore/AfterScenario` should probably become mutators on the suite.

**Pull request merged**
